[project]
name = "trie-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bs4>=0.0.2",
    "flask>=3.1.0",
    "httpx>=0.27.2",
    "lxml>=5.3.0",
    "pytest>=8.3.3",
    "ruff>=0.6.9",
]
